# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video_origin = QtWidgets.QLabel(self.centralwidget)
        self.label_video_origin.setGeometry(QtCore.QRect(580, 30, 341, 241))
        self.label_video_origin.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.33 rgba(0, 0, 0, 255), stop:0.34 rgba(255, 30, 30, 255), stop:0.66 rgba(255, 0, 0, 255), stop:0.67 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 0, 255));")
        self.label_video_origin.setText("")
        self.label_video_origin.setObjectName("label_video_origin")
        self.label_video_detect = QtWidgets.QLabel(self.centralwidget)
        self.label_video_detect.setGeometry(QtCore.QRect(580, 290, 341, 381))
        self.label_video_detect.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_video_detect.setText("")
        self.label_video_detect.setObjectName("label_video_detect")
        self.textBrowser_state = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_state.setGeometry(QtCore.QRect(30, 110, 491, 231))
        self.textBrowser_state.setObjectName("textBrowser_state")
        self.textBrowser_msg = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_msg.setGeometry(QtCore.QRect(30, 370, 491, 281))
        self.textBrowser_msg.setObjectName("textBrowser_msg")
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(30, 40, 131, 41))
        self.recordButton.setObjectName("recordButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(350, 40, 131, 41))
        self.playButton.setObjectName("playButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(190, 40, 131, 41))
        self.stopButton.setObjectName("stopButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.recordButton.setText(_translate("MainWindow", "录制"))
        self.playButton.setText(_translate("MainWindow", "播放"))
        self.stopButton.setText(_translate("MainWindow", "停止录制"))
